language: php
sudo: false

php:
#  - 5.5
  - 5.6
  - 7.0
  - hhvm
env:
  - WOO_VERSION="release/3.0" WP_VERSION=latest

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

install:
  - cd ..
  - git clone https://github.com/woocommerce/woocommerce
  - cd woocommerce/
  - git checkout $WOO_VERSION
  - bash tests/bin/install.sh woocommerce_test root '' localhost $WP_VERSION
  - echo 'if (!class_exists("\PHPUnit_Framework_TestCase", false) && class_exists("\PHPUnit\Framework\TestCase", false)) { class_alias("\PHPUnit\Framework\TestCase", "\PHPUnit_Framework_TestCase"); }' >> /tmp/wordpress-tests-lib/wp-tests-config.php
  - cd ..
  - cd PayEx.WooCommerce
script:
  - phpunit

notifications:
  email:
    recipients:
      - ottofromhell@gmail.com
    on_failure: always
