language: php
sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
env:
  - WOO_VERSION="2.6.4" WP_VERSION=latest
#  - WOO_VERSION="2.5.5" WP_VERSION=4.5
#  - WOO_VERSION="2.4.13" WP_VERSION=4.4

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

install:
  - cd ..
  - wget https://github.com/woothemes/woocommerce/archive/$WOO_VERSION.tar.gz -O woocommerce.tar.gz
  - tar zxf ./woocommerce.tar.gz
  - mv woocommerce-*/ woocommerce/
  - cd woocommerce/
  - bash tests/bin/install.sh woocommerce_test root '' localhost $WP_VERSION
  - cd ..
  - cd PayEx.WooCommerce
script:
  - phpunit

notifications:
  email:
    recipients:
      - ottofromhell@gmail.com
    on_failure: always
