sudo: false
dist: xenial
language: php
services:
  - mysql

php:
  - 7.1
  #- 7.2
  #- 7.3

env:
  - WOO_VERSION="3.6.5" WP_VERSION=latest

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.2

install:
  - cd ..
  - git clone https://github.com/woocommerce/woocommerce
  - cd woocommerce/
  - git checkout tags/$WOO_VERSION
  - bash tests/bin/install.sh woocommerce_test root '' 127.0.0.1 $WP_VERSION
  - cd ..
  - cd $TRAVIS_BUILD_DIR

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi

script:
  - |
    phpunit
    WP_MULTISITE=1 phpunit

notifications:
  email:
    recipients:
      - ottofromhell@gmail.com
    on_failure: always
