language: php
sudo: false

php:
  - 5.6
  - 7.0
  - hhvm
env:
  - WOO_VERSION="release/3.0" WP_VERSION=latest

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: 7.0

install:
  - cd ..
  - git clone https://github.com/woocommerce/woocommerce
  - cd woocommerce/
  - git checkout $WOO_VERSION
  - bash tests/bin/install.sh woocommerce_test root '' localhost $WP_VERSION
  - cd ..
  - cd PayEx.WooCommerce
script:
  - phpunit

notifications:
  email:
    recipients:
      - ottofromhell@gmail.com
    on_failure: always
