language: php
sudo: false
dist: bionic

services:
  - mysql

php:
  - 7.3

env:
  - WOO_VERSION="3.6.1" WP_VERSION=latest

install:
  - cd ..
  - git clone https://github.com/woocommerce/woocommerce
  - cd woocommerce/
  - git checkout tags/$WOO_VERSION
  - bash tests/bin/install.sh woocommerce_test root '' localhost $WP_VERSION
  - cd ..
  - cd PayEx.WooCommerce

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - curl -sSfL -o $HOME/.composer/vendor/bin/phpunit https://phar.phpunit.de/phpunit-7.phar
  - chmod +x $HOME/.composer/vendor/bin/phpunit

script:
  - $HOME/.composer/vendor/bin/phpunit

notifications:
  email:
    recipients:
      - ottofromhell@gmail.com
    on_failure: always
